; ==================================================================================================
; Title:   IntgSim.inc
; Author:  Héctor S. Enrique  @ March 2016
; Version: 1.0.0
; Purpose:  Functional Continuos Simulation - IntegAsm32 Light
; ==================================================================================================

% include IntgSim_OOP.inc

if IMPLEMENT
	% include IntgSim_macs.inc
	% include IntgSim_PROC.inc
endif
