; ==================================================================================================
; Title:   IntgBase.inc
; Author:  Héctor S. Enrique  @ October 2018
; Version: 1.0.0
; Purpose:  Continuos Integration - IntegAsm32 Light
; ==================================================================================================
%include IntgBase_OOP.inc
if IMPLEMENT
%include IntgBase_PROC.inc
ENDIF