;Include file created by h2incX, Version B.01.01, 22/10/2018 23:24
;(C) 2018-today by Biterider, 2005-2009 by Japheth
;Source file: '\ObjAsm\Projects\h2IncX\header\propsys.h', last modified: 19/04/2018 10:45
;Creation parameters: 

ifndef __REQUIRED_RPCNDR_H_VERSION__
  __REQUIRED_RPCNDR_H_VERSION__ equ 500
endif
ifndef __REQUIRED_RPCSAL_H_VERSION__
  __REQUIRED_RPCSAL_H_VERSION__ equ 100
endif
include rpc.inc
include rpcndr.inc
ifndef __RPCNDR_H_VERSION__
  .err <this stub requires an updated version of < rpcndr.h >>
endif
ifndef COM_NO_WINDOWS_H
  include windows.inc
  include ole2.inc
endif
ifndef __propsys_h__
  __propsys_h__ equ <>
  if Defined(_MSC_VER) and (_MSC_VER ge 1020)
  endif
  ifndef __IInitializeWithFile_FWD_DEFINED__
    __IInitializeWithFile_FWD_DEFINED__ equ <>
    ;IInitializeWithFile typedef IInitializeWithFile
    
  endif
  ifndef __IInitializeWithStream_FWD_DEFINED__
    __IInitializeWithStream_FWD_DEFINED__ equ <>
    ;IInitializeWithStream typedef IInitializeWithStream
    
  endif
  ifndef __IPropertyStore_FWD_DEFINED__
    __IPropertyStore_FWD_DEFINED__ equ <>
    ;IPropertyStore typedef IPropertyStore
    
  endif
  ifndef __INamedPropertyStore_FWD_DEFINED__
    __INamedPropertyStore_FWD_DEFINED__ equ <>
    ;INamedPropertyStore typedef INamedPropertyStore
    
  endif
  ifndef __IObjectWithPropertyKey_FWD_DEFINED__
    __IObjectWithPropertyKey_FWD_DEFINED__ equ <>
    ;IObjectWithPropertyKey typedef IObjectWithPropertyKey
    
  endif
  ifndef __IPropertyChange_FWD_DEFINED__
    __IPropertyChange_FWD_DEFINED__ equ <>
    ;IPropertyChange typedef IPropertyChange
    
  endif
  ifndef __IPropertyChangeArray_FWD_DEFINED__
    __IPropertyChangeArray_FWD_DEFINED__ equ <>
    ;IPropertyChangeArray typedef IPropertyChangeArray
    
  endif
  ifndef __IPropertyStoreCapabilities_FWD_DEFINED__
    __IPropertyStoreCapabilities_FWD_DEFINED__ equ <>
    ;IPropertyStoreCapabilities typedef IPropertyStoreCapabilities
    
  endif
  ifndef __IPropertyStoreCache_FWD_DEFINED__
    __IPropertyStoreCache_FWD_DEFINED__ equ <>
    ;IPropertyStoreCache typedef IPropertyStoreCache
    
  endif
  ifndef __IPropertyEnumType_FWD_DEFINED__
    __IPropertyEnumType_FWD_DEFINED__ equ <>
    ;IPropertyEnumType typedef IPropertyEnumType
    
  endif
  ifndef __IPropertyEnumType2_FWD_DEFINED__
    __IPropertyEnumType2_FWD_DEFINED__ equ <>
    ;IPropertyEnumType2 typedef IPropertyEnumType2
    
  endif
  ifndef __IPropertyEnumTypeList_FWD_DEFINED__
    __IPropertyEnumTypeList_FWD_DEFINED__ equ <>
    ;IPropertyEnumTypeList typedef IPropertyEnumTypeList
    
  endif
  ifndef __IPropertyDescription_FWD_DEFINED__
    __IPropertyDescription_FWD_DEFINED__ equ <>
    ;IPropertyDescription typedef IPropertyDescription
    
  endif
  ifndef __IPropertyDescription2_FWD_DEFINED__
    __IPropertyDescription2_FWD_DEFINED__ equ <>
    ;IPropertyDescription2 typedef IPropertyDescription2
    
  endif
  ifndef __IPropertyDescriptionAliasInfo_FWD_DEFINED__
    __IPropertyDescriptionAliasInfo_FWD_DEFINED__ equ <>
    ;IPropertyDescriptionAliasInfo typedef IPropertyDescriptionAliasInfo
    
  endif
  ifndef __IPropertyDescriptionSearchInfo_FWD_DEFINED__
    __IPropertyDescriptionSearchInfo_FWD_DEFINED__ equ <>
    ;IPropertyDescriptionSearchInfo typedef IPropertyDescriptionSearchInfo
    
  endif
  ifndef __IPropertyDescriptionRelatedPropertyInfo_FWD_DEFINED__
    __IPropertyDescriptionRelatedPropertyInfo_FWD_DEFINED__ equ <>
    ;IPropertyDescriptionRelatedPropertyInfo typedef IPropertyDescriptionRelatedPropertyInfo
    
  endif
  ifndef __IPropertySystem_FWD_DEFINED__
    __IPropertySystem_FWD_DEFINED__ equ <>
    ;IPropertySystem typedef IPropertySystem
    
  endif
  ifndef __IPropertyDescriptionList_FWD_DEFINED__
    __IPropertyDescriptionList_FWD_DEFINED__ equ <>
    ;IPropertyDescriptionList typedef IPropertyDescriptionList
    
  endif
  ifndef __IPropertyStoreFactory_FWD_DEFINED__
    __IPropertyStoreFactory_FWD_DEFINED__ equ <>
    ;IPropertyStoreFactory typedef IPropertyStoreFactory
    
  endif
  ifndef __IDelayedPropertyStoreFactory_FWD_DEFINED__
    __IDelayedPropertyStoreFactory_FWD_DEFINED__ equ <>
    ;IDelayedPropertyStoreFactory typedef IDelayedPropertyStoreFactory
    
  endif
  ifndef __IPersistSerializedPropStorage_FWD_DEFINED__
    __IPersistSerializedPropStorage_FWD_DEFINED__ equ <>
    ;IPersistSerializedPropStorage typedef IPersistSerializedPropStorage
    
  endif
  ifndef __IPersistSerializedPropStorage2_FWD_DEFINED__
    __IPersistSerializedPropStorage2_FWD_DEFINED__ equ <>
    ;IPersistSerializedPropStorage2 typedef IPersistSerializedPropStorage2
    
  endif
  ifndef __IPropertySystemChangeNotify_FWD_DEFINED__
    __IPropertySystemChangeNotify_FWD_DEFINED__ equ <>
    ;IPropertySystemChangeNotify typedef IPropertySystemChangeNotify
    
  endif
  ifndef __ICreateObject_FWD_DEFINED__
    __ICreateObject_FWD_DEFINED__ equ <>
    ;ICreateObject typedef ICreateObject
    
  endif
  ifndef __InMemoryPropertyStore_FWD_DEFINED__
    __InMemoryPropertyStore_FWD_DEFINED__ equ <>
    ifdef __cplusplus
      ;[...]
    else
      ;InMemoryPropertyStore typedef InMemoryPropertyStore
      
    endif
  endif
  ifndef __InMemoryPropertyStoreMarshalByValue_FWD_DEFINED__
    __InMemoryPropertyStoreMarshalByValue_FWD_DEFINED__ equ <>
    ifdef __cplusplus
      ;[...]
    else
      ;InMemoryPropertyStoreMarshalByValue typedef InMemoryPropertyStoreMarshalByValue
      
    endif
  endif
  ifndef __PropertySystem_FWD_DEFINED__
    __PropertySystem_FWD_DEFINED__ equ <>
    ifdef __cplusplus
      ;[...]
    else
      ;PropertySystem typedef PropertySystem
      
    endif
  endif
  include objidl.inc
  include oleidl.inc
  include ocidl.inc
  include shtypes.inc
  include StructuredQueryCondition.inc
  ifdef __cplusplus
    ;[...]
  endif
  include winapifamily.inc
  ifndef PSSTDAPI
    if Defined(_PROPSYS_)
      PSSTDAPI equ <STDAPI>
      PSSTDAPI_ macro type_
        exitm <STDAPI_(type_)>
      endm
    else
      PSSTDAPI equ <EXTERN_C DECLSPEC_IMPORT HRESULT STDAPICALLTYPE>
      PSSTDAPI_ macro type_
        exitm <EXTERN_C DECLSPEC_IMPORT type_ STDAPICALLTYPE>
      endm
    endif
  endif
  if 0
    ;[...]
  endif
  include propkeydef.inc
  if WINAPI_FAMILY_PARTITION(WINAPI_PARTITION_DESKTOP)
    if _MSC_VER ge 1200
      ifndef _MSC_EXTENSIONS
      endif
    endif
    externdef __MIDL_itf_propsys_0000_0000_v0_0_c_ifspec:RPC_IF_HANDLE
    externdef __MIDL_itf_propsys_0000_0000_v0_0_s_ifspec:RPC_IF_HANDLE
    ifndef __IInitializeWithFile_INTERFACE_DEFINED__
      __IInitializeWithFile_INTERFACE_DEFINED__ equ <>
      externdef IID_IInitializeWithFile:IID
      if Defined(__cplusplus) and  not Defined(CINTERFACE)
        ;[...]
      else
        IInitializeWithFileVtbl struct
          BEGIN_INTERFACE
          ??Interface equ <IInitializeWithFileVtbl>
          STD_METHOD QueryInterface, :ptr IInitializeWithFile, :REFIID, :ptr ptr
          STD_METHOD AddRef, :ptr IInitializeWithFile
          STD_METHOD Release, :ptr IInitializeWithFile
          STD_METHOD Initialize, :ptr IInitializeWithFile, :LPCWSTR, :DWORD
          ??Interface equ <>
          END_INTERFACE
        IInitializeWithFileVtbl ends
        IInitializeWithFile struct
          lpVtbl POINTER ?
        IInitializeWithFile ends
        ifdef COBJMACROS
          ;[...]
        endif
      endif
    endif
    ifndef __IInitializeWithStream_INTERFACE_DEFINED__
      __IInitializeWithStream_INTERFACE_DEFINED__ equ <>
      externdef IID_IInitializeWithStream:IID
      if Defined(__cplusplus) and  not Defined(CINTERFACE)
        ;[...]
      else
        IInitializeWithStreamVtbl struct
          BEGIN_INTERFACE
          ??Interface equ <IInitializeWithStreamVtbl>
          STD_METHOD QueryInterface, :ptr IInitializeWithStream, :REFIID, :ptr ptr
          STD_METHOD AddRef, :ptr IInitializeWithStream
          STD_METHOD Release, :ptr IInitializeWithStream
          STD_METHOD Initialize, :ptr IInitializeWithStream, :ptr IStream, :DWORD
          ??Interface equ <>
          END_INTERFACE
        IInitializeWithStreamVtbl ends
        IInitializeWithStream struct
          lpVtbl POINTER ?
        IInitializeWithStream ends
        ifdef COBJMACROS
          ;[...]
        endif
      endif
      IInitializeWithStream_RemoteInitialize_Proxy proto WIN_STD_CALL_CONV :ptr IInitializeWithStream, :ptr IStream, :DWORD
      IInitializeWithStream_RemoteInitialize_Stub proto WIN_STD_CALL_CONV :ptr IRpcStubBuffer, :ptr IRpcChannelBuffer, :PRPC_MESSAGE, :ptr DWORD
    endif
  endif
  if WINAPI_FAMILY_PARTITION(WINAPI_PARTITION_APP)
    externdef __MIDL_itf_propsys_0000_0002_v0_0_c_ifspec:RPC_IF_HANDLE
    externdef __MIDL_itf_propsys_0000_0002_v0_0_s_ifspec:RPC_IF_HANDLE
    ifndef __IPropertyStore_INTERFACE_DEFINED__
      __IPropertyStore_INTERFACE_DEFINED__ equ <>
      externdef IID_IPropertyStore:IID
      if Defined(__cplusplus) and  not Defined(CINTERFACE)
        ;[...]
      else
        IPropertyStoreVtbl struct
          BEGIN_INTERFACE
          ??Interface equ <IPropertyStoreVtbl>
          STD_METHOD QueryInterface, :ptr IPropertyStore, :REFIID, :ptr ptr
          STD_METHOD AddRef, :ptr IPropertyStore
          STD_METHOD Release, :ptr IPropertyStore
          STD_METHOD GetCount, :ptr IPropertyStore, :ptr DWORD
          STD_METHOD GetAt, :ptr IPropertyStore, :DWORD, :ptr PROPERTYKEY
          STD_METHOD GetValue, :ptr IPropertyStore, :REFPROPERTYKEY, :ptr PROPVARIANT
          STD_METHOD SetValue, :ptr IPropertyStore, :REFPROPERTYKEY, :REFPROPVARIANT
          STD_METHOD Commit, :ptr IPropertyStore
          ??Interface equ <>
          END_INTERFACE
        IPropertyStoreVtbl ends
        IPropertyStore struct
          lpVtbl POINTER ?
        IPropertyStore ends
        ifdef COBJMACROS
          ;[...]
        endif
      endif
    endif
    LPPROPERTYSTORE typedef ptr IPropertyStore
    @DefProto DllImport, PropVariantToWinRTPropertyValue, WIN_STD_CALL_CONV,, <:REFPROPVARIANT, :REFIID, :ptr ptr>, 12
    @DefProto DllImport, WinRTPropertyValueToPropVariant, WIN_STD_CALL_CONV,, <:ptr IUnknown, :ptr PROPVARIANT>, 8
  endif
  if WINAPI_FAMILY_PARTITION(WINAPI_PARTITION_DESKTOP)
    externdef __MIDL_itf_propsys_0000_0003_v0_0_c_ifspec:RPC_IF_HANDLE
    externdef __MIDL_itf_propsys_0000_0003_v0_0_s_ifspec:RPC_IF_HANDLE
    ifndef __INamedPropertyStore_INTERFACE_DEFINED__
      __INamedPropertyStore_INTERFACE_DEFINED__ equ <>
      externdef IID_INamedPropertyStore:IID
      if Defined(__cplusplus) and  not Defined(CINTERFACE)
        ;[...]
      else
        INamedPropertyStoreVtbl struct
          BEGIN_INTERFACE
          ??Interface equ <INamedPropertyStoreVtbl>
          STD_METHOD QueryInterface, :ptr INamedPropertyStore, :REFIID, :ptr ptr
          STD_METHOD AddRef, :ptr INamedPropertyStore
          STD_METHOD Release, :ptr INamedPropertyStore
          STD_METHOD GetNamedValue, :ptr INamedPropertyStore, :LPCWSTR, :ptr PROPVARIANT
          STD_METHOD SetNamedValue, :ptr INamedPropertyStore, :LPCWSTR, :REFPROPVARIANT
          STD_METHOD GetNameCount, :ptr INamedPropertyStore, :ptr DWORD
          STD_METHOD GetNameAt, :ptr INamedPropertyStore, :DWORD, :ptr BSTR
          ??Interface equ <>
          END_INTERFACE
        INamedPropertyStoreVtbl ends
        INamedPropertyStore struct
          lpVtbl POINTER ?
        INamedPropertyStore ends
        ifdef COBJMACROS
          ;[...]
        endif
      endif
    endif
    GETPROPERTYSTOREFLAGS typedef SDWORD
    GPS_DEFAULT equ 0
    GPS_HANDLERPROPERTIESONLY equ 1h
    GPS_READWRITE equ 2h
    GPS_TEMPORARY equ 4h
    GPS_FASTPROPERTIESONLY equ 8h
    GPS_OPENSLOWITEM equ 10h
    GPS_DELAYCREATION equ 20h
    GPS_BESTEFFORT equ 40h
    GPS_NO_OPLOCK equ 80h
    GPS_PREFERQUERYPROPERTIES equ 100h
    GPS_EXTRINSICPROPERTIES equ 200h
    GPS_EXTRINSICPROPERTIESONLY equ 400h
    GPS_VOLATILEPROPERTIES equ 800h
    GPS_VOLATILEPROPERTIESONLY equ 1000h
    GPS_MASK_VALID equ 1fffh
    
    DEFINE_ENUM_FLAG_OPERATORS(GETPROPERTYSTOREFLAGS)
    externdef __MIDL_itf_propsys_0000_0004_v0_0_c_ifspec:RPC_IF_HANDLE
    externdef __MIDL_itf_propsys_0000_0004_v0_0_s_ifspec:RPC_IF_HANDLE
    ifndef __IObjectWithPropertyKey_INTERFACE_DEFINED__
      __IObjectWithPropertyKey_INTERFACE_DEFINED__ equ <>
      externdef IID_IObjectWithPropertyKey:IID
      if Defined(__cplusplus) and  not Defined(CINTERFACE)
        ;[...]
      else
        IObjectWithPropertyKeyVtbl struct
          BEGIN_INTERFACE
          ??Interface equ <IObjectWithPropertyKeyVtbl>
          STD_METHOD QueryInterface, :ptr IObjectWithPropertyKey, :REFIID, :ptr ptr
          STD_METHOD AddRef, :ptr IObjectWithPropertyKey
          STD_METHOD Release, :ptr IObjectWithPropertyKey
          STD_METHOD SetPropertyKey, :ptr IObjectWithPropertyKey, :REFPROPERTYKEY
          STD_METHOD GetPropertyKey, :ptr IObjectWithPropertyKey, :ptr PROPERTYKEY
          ??Interface equ <>
          END_INTERFACE
        IObjectWithPropertyKeyVtbl ends
        IObjectWithPropertyKey struct
          lpVtbl POINTER ?
        IObjectWithPropertyKey ends
        ifdef COBJMACROS
          ;[...]
        endif
      endif
    endif
    PKA_FLAGS typedef SDWORD
    PKA_SET equ 0
    PKA_APPEND equ
    PKA_DELETE equ
    
    externdef __MIDL_itf_propsys_0000_0005_v0_0_c_ifspec:RPC_IF_HANDLE
    externdef __MIDL_itf_propsys_0000_0005_v0_0_s_ifspec:RPC_IF_HANDLE
    ifndef __IPropertyChange_INTERFACE_DEFINED__
      __IPropertyChange_INTERFACE_DEFINED__ equ <>
      externdef IID_IPropertyChange:IID
      if Defined(__cplusplus) and  not Defined(CINTERFACE)
        ;[...]
      else
        IPropertyChangeVtbl struct
          BEGIN_INTERFACE
          ??Interface equ <IPropertyChangeVtbl>
          STD_METHOD QueryInterface, :ptr IPropertyChange, :REFIID, :ptr ptr
          STD_METHOD AddRef, :ptr IPropertyChange
          STD_METHOD Release, :ptr IPropertyChange
          STD_METHOD SetPropertyKey, :ptr IPropertyChange, :REFPROPERTYKEY
          STD_METHOD GetPropertyKey, :ptr IPropertyChange, :ptr PROPERTYKEY
          STD_METHOD ApplyToPropVariant, :ptr IPropertyChange, :REFPROPVARIANT, :ptr PROPVARIANT
          ??Interface equ <>
          END_INTERFACE
        IPropertyChangeVtbl ends
        IPropertyChange struct
          lpVtbl POINTER ?
        IPropertyChange ends
        ifdef COBJMACROS
          ;[...]
        endif
      endif
    endif
    ifndef __IPropertyChangeArray_INTERFACE_DEFINED__
      __IPropertyChangeArray_INTERFACE_DEFINED__ equ <>
      externdef IID_IPropertyChangeArray:IID
      if Defined(__cplusplus) and  not Defined(CINTERFACE)
        ;[...]
      else
        IPropertyChangeArrayVtbl struct
          BEGIN_INTERFACE
          ??Interface equ <IPropertyChangeArrayVtbl>
          STD_METHOD QueryInterface, :ptr IPropertyChangeArray, :REFIID, :ptr ptr
          STD_METHOD AddRef, :ptr IPropertyChangeArray
          STD_METHOD Release, :ptr IPropertyChangeArray
          STD_METHOD GetCount, :ptr IPropertyChangeArray, :ptr UINT
          STD_METHOD GetAt, :ptr IPropertyChangeArray, :UINT, :REFIID, :ptr ptr
          STD_METHOD InsertAt, :ptr IPropertyChangeArray, :UINT, :ptr IPropertyChange
          STD_METHOD Append, :ptr IPropertyChangeArray, :ptr IPropertyChange
          STD_METHOD AppendOrReplace, :ptr IPropertyChangeArray, :ptr IPropertyChange
          STD_METHOD RemoveAt, :ptr IPropertyChangeArray, :UINT
          STD_METHOD IsKeyInArray, :ptr IPropertyChangeArray, :REFPROPERTYKEY
          ??Interface equ <>
          END_INTERFACE
        IPropertyChangeArrayVtbl ends
        IPropertyChangeArray struct
          lpVtbl POINTER ?
        IPropertyChangeArray ends
        ifdef COBJMACROS
          ;[...]
        endif
      endif
    endif
    ifndef __IPropertyStoreCapabilities_INTERFACE_DEFINED__
      __IPropertyStoreCapabilities_INTERFACE_DEFINED__ equ <>
      externdef IID_IPropertyStoreCapabilities:IID
      if Defined(__cplusplus) and  not Defined(CINTERFACE)
        ;[...]
      else
        IPropertyStoreCapabilitiesVtbl struct
          BEGIN_INTERFACE
          ??Interface equ <IPropertyStoreCapabilitiesVtbl>
          STD_METHOD QueryInterface, :ptr IPropertyStoreCapabilities, :REFIID, :ptr ptr
          STD_METHOD AddRef, :ptr IPropertyStoreCapabilities
          STD_METHOD Release, :ptr IPropertyStoreCapabilities
          STD_METHOD IsPropertyWritable, :ptr IPropertyStoreCapabilities, :REFPROPERTYKEY
          ??Interface equ <>
          END_INTERFACE
        IPropertyStoreCapabilitiesVtbl ends
        IPropertyStoreCapabilities struct
          lpVtbl POINTER ?
        IPropertyStoreCapabilities ends
        ifdef COBJMACROS
          ;[...]
        endif
      endif
    endif
    ifndef __IPropertyStoreCache_INTERFACE_DEFINED__
      __IPropertyStoreCache_INTERFACE_DEFINED__ equ <>
      PSC_STATE typedef SDWORD
      PSC_NORMAL equ 0
      PSC_NOTINSOURCE equ 1
      PSC_DIRTY equ 2
      PSC_READONLY equ 3
      
      externdef IID_IPropertyStoreCache:IID
      if Defined(__cplusplus) and  not Defined(CINTERFACE)
        ;[...]
      else
        IPropertyStoreCacheVtbl struct
          BEGIN_INTERFACE
          ??Interface equ <IPropertyStoreCacheVtbl>
          STD_METHOD QueryInterface, :ptr IPropertyStoreCache, :REFIID, :ptr ptr
          STD_METHOD AddRef, :ptr IPropertyStoreCache
          STD_METHOD Release, :ptr IPropertyStoreCache
          STD_METHOD GetCount, :ptr IPropertyStoreCache, :ptr DWORD
          STD_METHOD GetAt, :ptr IPropertyStoreCache, :DWORD, :ptr PROPERTYKEY
          STD_METHOD GetValue, :ptr IPropertyStoreCache, :REFPROPERTYKEY, :ptr PROPVARIANT
          STD_METHOD SetValue, :ptr IPropertyStoreCache, :REFPROPERTYKEY, :REFPROPVARIANT
          STD_METHOD Commit, :ptr IPropertyStoreCache
          STD_METHOD GetState, :ptr IPropertyStoreCache, :REFPROPERTYKEY, :ptr PSC_STATE
          STD_METHOD GetValueAndState, :ptr IPropertyStoreCache, :REFPROPERTYKEY, :ptr PROPVARIANT, :ptr PSC_STATE
          STD_METHOD SetState, :ptr IPropertyStoreCache, :REFPROPERTYKEY, :PSC_STATE
          STD_METHOD SetValueAndState, :ptr IPropertyStoreCache, :REFPROPERTYKEY, :ptr PROPVARIANT, :PSC_STATE
          ??Interface equ <>
          END_INTERFACE
        IPropertyStoreCacheVtbl ends
        IPropertyStoreCache struct
          lpVtbl POINTER ?
        IPropertyStoreCache ends
        ifdef COBJMACROS
          ;[...]
        endif
      endif
    endif
    ifndef __IPropertyEnumType_INTERFACE_DEFINED__
      __IPropertyEnumType_INTERFACE_DEFINED__ equ <>
      PROPENUMTYPE typedef SDWORD
      PET_DISCRETEVALUE equ 0
      PET_RANGEDVALUE equ 1
      PET_DEFAULTVALUE equ 2
      PET_ENDRANGE equ 3
      
      externdef IID_IPropertyEnumType:IID
      if Defined(__cplusplus) and  not Defined(CINTERFACE)
        ;[...]
      else
        IPropertyEnumTypeVtbl struct
          BEGIN_INTERFACE
          ??Interface equ <IPropertyEnumTypeVtbl>
          STD_METHOD QueryInterface, :ptr IPropertyEnumType, :REFIID, :ptr ptr
          STD_METHOD AddRef, :ptr IPropertyEnumType
          STD_METHOD Release, :ptr IPropertyEnumType
          STD_METHOD GetEnumType, :ptr IPropertyEnumType, :ptr PROPENUMTYPE
          STD_METHOD GetValue, :ptr IPropertyEnumType, :ptr PROPVARIANT
          STD_METHOD GetRangeMinValue, :ptr IPropertyEnumType, :ptr PROPVARIANT
          STD_METHOD GetRangeSetValue, :ptr IPropertyEnumType, :ptr PROPVARIANT
          STD_METHOD GetDisplayText, :ptr IPropertyEnumType, :ptr LPWSTR
          ??Interface equ <>
          END_INTERFACE
        IPropertyEnumTypeVtbl ends
        IPropertyEnumType struct
          lpVtbl POINTER ?
        IPropertyEnumType ends
        ifdef COBJMACROS
          ;[...]
        endif
      endif
    endif
    ifndef __IPropertyEnumType2_INTERFACE_DEFINED__
      __IPropertyEnumType2_INTERFACE_DEFINED__ equ <>
      externdef IID_IPropertyEnumType2:IID
      if Defined(__cplusplus) and  not Defined(CINTERFACE)
        ;[...]
      else
        IPropertyEnumType2Vtbl struct
          BEGIN_INTERFACE
          ??Interface equ <IPropertyEnumType2Vtbl>
          STD_METHOD QueryInterface, :ptr IPropertyEnumType2, :REFIID, :ptr ptr
          STD_METHOD AddRef, :ptr IPropertyEnumType2
          STD_METHOD Release, :ptr IPropertyEnumType2
          STD_METHOD GetEnumType, :ptr IPropertyEnumType2, :ptr PROPENUMTYPE
          STD_METHOD GetValue, :ptr IPropertyEnumType2, :ptr PROPVARIANT
          STD_METHOD GetRangeMinValue, :ptr IPropertyEnumType2, :ptr PROPVARIANT
          STD_METHOD GetRangeSetValue, :ptr IPropertyEnumType2, :ptr PROPVARIANT
          STD_METHOD GetDisplayText, :ptr IPropertyEnumType2, :ptr LPWSTR
          STD_METHOD GetImageReference, :ptr IPropertyEnumType2, :ptr LPWSTR
          ??Interface equ <>
          END_INTERFACE
        IPropertyEnumType2Vtbl ends
        IPropertyEnumType2 struct
          lpVtbl POINTER ?
        IPropertyEnumType2 ends
        ifdef COBJMACROS
          ;[...]
        endif
      endif
    endif
    ifndef __IPropertyEnumTypeList_INTERFACE_DEFINED__
      __IPropertyEnumTypeList_INTERFACE_DEFINED__ equ <>
      externdef IID_IPropertyEnumTypeList:IID
      if Defined(__cplusplus) and  not Defined(CINTERFACE)
        ;[...]
      else
        IPropertyEnumTypeListVtbl struct
          BEGIN_INTERFACE
          ??Interface equ <IPropertyEnumTypeListVtbl>
          STD_METHOD QueryInterface, :ptr IPropertyEnumTypeList, :REFIID, :ptr ptr
          STD_METHOD AddRef, :ptr IPropertyEnumTypeList
          STD_METHOD Release, :ptr IPropertyEnumTypeList
          STD_METHOD GetCount, :ptr IPropertyEnumTypeList, :ptr UINT
          STD_METHOD GetAt, :ptr IPropertyEnumTypeList, :UINT, :REFIID, :ptr ptr
          STD_METHOD GetConditionAt, :ptr IPropertyEnumTypeList, :UINT, :REFIID, :ptr ptr
          STD_METHOD FindMatchingIndex, :ptr IPropertyEnumTypeList, :REFPROPVARIANT, :ptr UINT
          ??Interface equ <>
          END_INTERFACE
        IPropertyEnumTypeListVtbl ends
        IPropertyEnumTypeList struct
          lpVtbl POINTER ?
        IPropertyEnumTypeList ends
        ifdef COBJMACROS
          ;[...]
        endif
      endif
    endif
    ifndef __IPropertyDescription_INTERFACE_DEFINED__
      __IPropertyDescription_INTERFACE_DEFINED__ equ <>
      PROPDESC_TYPE_FLAGS typedef SDWORD
      PDTF_DEFAULT equ 0
      PDTF_MULTIPLEVALUES equ 1h
      PDTF_ISINNATE equ 2h
      PDTF_ISGROUP equ 4h
      PDTF_CANGROUPBY equ 8h
      PDTF_CANSTACKBY equ 10h
      PDTF_ISTREEPROPERTY equ 20h
      PDTF_INCLUDEINFULLTEXTQUERY equ 40h
      PDTF_ISVIEWABLE equ 80h
      PDTF_ISQUERYABLE equ 100h
      PDTF_CANBEPURGED equ 200h
      PDTF_SEARCHRAWVALUE equ 400h
      PDTF_DONTCOERCEEMPTYSTRINGS equ 800h
      PDTF_ALWAYSINSUPPLEMENTALSTORE equ 1000h
      PDTF_ISSYSTEMPROPERTY equ 80000000h
      PDTF_MASK_ALL equ 80001fffh
      
      DEFINE_ENUM_FLAG_OPERATORS(PROPDESC_TYPE_FLAGS)
      PROPDESC_VIEW_FLAGS typedef SDWORD
      PDVF_DEFAULT equ 0
      PDVF_CENTERALIGN equ 1h
      PDVF_RIGHTALIGN equ 2h
      PDVF_BEGINNEWGROUP equ 4h
      PDVF_FILLAREA equ 8h
      PDVF_SORTDESCENDING equ 10h
      PDVF_SHOWONLYIFPRESENT equ 20h
      PDVF_SHOWBYDEFAULT equ 40h
      PDVF_SHOWINPRIMARYLIST equ 80h
      PDVF_SHOWINSECONDARYLIST equ 100h
      PDVF_HIDELABEL equ 200h
      PDVF_HIDDEN equ 800h
      PDVF_CANWRAP equ 1000h
      PDVF_MASK_ALL equ 1bffh
      
      DEFINE_ENUM_FLAG_OPERATORS(PROPDESC_VIEW_FLAGS)
      PROPDESC_DISPLAYTYPE typedef SDWORD
      PDDT_STRING equ 0
      PDDT_NUMBER equ 1
      PDDT_BOOLEAN equ 2
      PDDT_DATETIME equ 3
      PDDT_ENUMERATED equ 4
      
      PROPDESC_GROUPING_RANGE typedef SDWORD
      PDGR_DISCRETE equ 0
      PDGR_ALPHANUMERIC equ 1
      PDGR_SIZE equ 2
      PDGR_DYNAMIC equ 3
      PDGR_DATE equ 4
      PDGR_PERCENT equ 5
      PDGR_ENUMERATED equ 6
      
      PROPDESC_FORMAT_FLAGS typedef SDWORD
      PDFF_DEFAULT equ 0
      PDFF_PREFIXNAME equ 1h
      PDFF_FILENAME equ 2h
      PDFF_ALWAYSKB equ 4h
      PDFF_RESERVED_RIGHTTOLEFT equ 8h
      PDFF_SHORTTIME equ 10h
      PDFF_LONGTIME equ 20h
      PDFF_HIDETIME equ 40h
      PDFF_SHORTDATE equ 80h
      PDFF_LONGDATE equ 100h
      PDFF_HIDEDATE equ 200h
      PDFF_RELATIVEDATE equ 400h
      PDFF_USEEDITINVITATION equ 800h
      PDFF_READONLY equ 1000h
      PDFF_NOAUTOREADINGORDER equ 2000h
      
      DEFINE_ENUM_FLAG_OPERATORS(PROPDESC_FORMAT_FLAGS)
      PROPDESC_SORTDESCRIPTION typedef SDWORD
      PDSD_GENERAL equ 0
      PDSD_A_Z equ 1
      PDSD_LOWEST_HIGHEST equ 2
      PDSD_SMALLEST_BIGGEST equ 3
      PDSD_OLDEST_NEWEST equ 4
      
      PROPDESC_RELATIVEDESCRIPTION_TYPE typedef SDWORD
      PDRDT_GENERAL equ 0
      PDRDT_DATE equ 1
      PDRDT_SIZE equ 2
      PDRDT_COUNT equ 3
      PDRDT_REVISION equ 4
      PDRDT_LENGTH equ 5
      PDRDT_DURATION equ 6
      PDRDT_SPEED equ 7
      PDRDT_RATE equ 8
      PDRDT_RATING equ 9
      PDRDT_PRIORITY equ 10
      
      PROPDESC_AGGREGATION_TYPE typedef SDWORD
      PDAT_DEFAULT equ 0
      PDAT_FIRST equ 1
      PDAT_SUM equ 2
      PDAT_AVERAGE equ 3
      PDAT_DATERANGE equ 4
      PDAT_UNION equ 5
      PDAT_MAX equ 6
      PDAT_MIN equ 7
      
      PROPDESC_CONDITION_TYPE typedef SDWORD
      PDCOT_NONE equ 0
      PDCOT_STRING equ 1
      PDCOT_SIZE equ 2
      PDCOT_DATETIME equ 3
      PDCOT_BOOLEAN equ 4
      PDCOT_NUMBER equ 5
      
      externdef IID_IPropertyDescription:IID
      if Defined(__cplusplus) and  not Defined(CINTERFACE)
        ;[...]
      else
        IPropertyDescriptionVtbl struct
          BEGIN_INTERFACE
          ??Interface equ <IPropertyDescriptionVtbl>
          STD_METHOD QueryInterface, :ptr IPropertyDescription, :REFIID, :ptr ptr
          STD_METHOD AddRef, :ptr IPropertyDescription
          STD_METHOD Release, :ptr IPropertyDescription
          STD_METHOD GetPropertyKey, :ptr IPropertyDescription, :ptr PROPERTYKEY
          STD_METHOD GetCanonicalName, :ptr IPropertyDescription, :ptr LPWSTR
          STD_METHOD GetPropertyType, :ptr IPropertyDescription, :ptr VARTYPE
          STD_METHOD GetDisplayName, :ptr IPropertyDescription, :ptr LPWSTR
          STD_METHOD GetEditInvitation, :ptr IPropertyDescription, :ptr LPWSTR
          STD_METHOD GetTypeFlags, :ptr IPropertyDescription, :PROPDESC_TYPE_FLAGS, :ptr PROPDESC_TYPE_FLAGS
          STD_METHOD GetViewFlags, :ptr IPropertyDescription, :ptr PROPDESC_VIEW_FLAGS
          STD_METHOD GetDefaultColumnWidth, :ptr IPropertyDescription, :ptr UINT
          STD_METHOD GetDisplayType, :ptr IPropertyDescription, :ptr PROPDESC_DISPLAYTYPE
          STD_METHOD GetColumnState, :ptr IPropertyDescription, :ptr SHCOLSTATEF
          STD_METHOD GetGroupingRange, :ptr IPropertyDescription, :ptr PROPDESC_GROUPING_RANGE
          STD_METHOD GetRelativeDescriptionType, :ptr IPropertyDescription, :ptr PROPDESC_RELATIVEDESCRIPTION_TYPE
          STD_METHOD GetRelativeDescription, :ptr IPropertyDescription, :REFPROPVARIANT, :REFPROPVARIANT, :ptr LPWSTR, :ptr LPWSTR
          STD_METHOD GetSortDescription, :ptr IPropertyDescription, :ptr PROPDESC_SORTDESCRIPTION
          STD_METHOD GetSortDescriptionLabel, :ptr IPropertyDescription, :BOOL, :ptr LPWSTR
          STD_METHOD GetAggregationType, :ptr IPropertyDescription, :ptr PROPDESC_AGGREGATION_TYPE
          STD_METHOD GetConditionType, :ptr IPropertyDescription, :ptr PROPDESC_CONDITION_TYPE, :ptr CONDITION_OPERATION
          STD_METHOD GetEnumTypeList, :ptr IPropertyDescription, :REFIID, :ptr ptr
          STD_METHOD CoerceToCanonicalValue, :ptr IPropertyDescription, :ptr PROPVARIANT
          STD_METHOD FormatForDisplay, :ptr IPropertyDescription, :REFPROPVARIANT, :PROPDESC_FORMAT_FLAGS, :ptr LPWSTR
          STD_METHOD IsValueCanonical, :ptr IPropertyDescription, :REFPROPVARIANT
          ??Interface equ <>
          END_INTERFACE
        IPropertyDescriptionVtbl ends
        IPropertyDescription struct
          lpVtbl POINTER ?
        IPropertyDescription ends
        ifdef COBJMACROS
          ;[...]
        endif
      endif
      IPropertyDescription_RemoteCoerceToCanonicalValue_Proxy proto WIN_STD_CALL_CONV :ptr IPropertyDescription, :REFPROPVARIANT, :ptr PROPVARIANT
      IPropertyDescription_RemoteCoerceToCanonicalValue_Stub proto WIN_STD_CALL_CONV :ptr IRpcStubBuffer, :ptr IRpcChannelBuffer, :PRPC_MESSAGE, :ptr DWORD
    endif
    ifndef __IPropertyDescription2_INTERFACE_DEFINED__
      __IPropertyDescription2_INTERFACE_DEFINED__ equ <>
      externdef IID_IPropertyDescription2:IID
      if Defined(__cplusplus) and  not Defined(CINTERFACE)
        ;[...]
      else
        IPropertyDescription2Vtbl struct
          BEGIN_INTERFACE
          ??Interface equ <IPropertyDescription2Vtbl>
          STD_METHOD QueryInterface, :ptr IPropertyDescription2, :REFIID, :ptr ptr
          STD_METHOD AddRef, :ptr IPropertyDescription2
          STD_METHOD Release, :ptr IPropertyDescription2
          STD_METHOD GetPropertyKey, :ptr IPropertyDescription2, :ptr PROPERTYKEY
          STD_METHOD GetCanonicalName, :ptr IPropertyDescription2, :ptr LPWSTR
          STD_METHOD GetPropertyType, :ptr IPropertyDescription2, :ptr VARTYPE
          STD_METHOD GetDisplayName, :ptr IPropertyDescription2, :ptr LPWSTR
          STD_METHOD GetEditInvitation, :ptr IPropertyDescription2, :ptr LPWSTR
          STD_METHOD GetTypeFlags, :ptr IPropertyDescription2, :PROPDESC_TYPE_FLAGS, :ptr PROPDESC_TYPE_FLAGS
          STD_METHOD GetViewFlags, :ptr IPropertyDescription2, :ptr PROPDESC_VIEW_FLAGS
          STD_METHOD GetDefaultColumnWidth, :ptr IPropertyDescription2, :ptr UINT
          STD_METHOD GetDisplayType, :ptr IPropertyDescription2, :ptr PROPDESC_DISPLAYTYPE
          STD_METHOD GetColumnState, :ptr IPropertyDescription2, :ptr SHCOLSTATEF
          STD_METHOD GetGroupingRange, :ptr IPropertyDescription2, :ptr PROPDESC_GROUPING_RANGE
          STD_METHOD GetRelativeDescriptionType, :ptr IPropertyDescription2, :ptr PROPDESC_RELATIVEDESCRIPTION_TYPE
          STD_METHOD GetRelativeDescription, :ptr IPropertyDescription2, :REFPROPVARIANT, :REFPROPVARIANT, :ptr LPWSTR, :ptr LPWSTR
          STD_METHOD GetSortDescription, :ptr IPropertyDescription2, :ptr PROPDESC_SORTDESCRIPTION
          STD_METHOD GetSortDescriptionLabel, :ptr IPropertyDescription2, :BOOL, :ptr LPWSTR
          STD_METHOD GetAggregationType, :ptr IPropertyDescription2, :ptr PROPDESC_AGGREGATION_TYPE
          STD_METHOD GetConditionType, :ptr IPropertyDescription2, :ptr PROPDESC_CONDITION_TYPE, :ptr CONDITION_OPERATION
          STD_METHOD GetEnumTypeList, :ptr IPropertyDescription2, :REFIID, :ptr ptr
          STD_METHOD CoerceToCanonicalValue, :ptr IPropertyDescription2, :ptr PROPVARIANT
          STD_METHOD FormatForDisplay, :ptr IPropertyDescription2, :REFPROPVARIANT, :PROPDESC_FORMAT_FLAGS, :ptr LPWSTR
          STD_METHOD IsValueCanonical, :ptr IPropertyDescription2, :REFPROPVARIANT
          STD_METHOD GetImageReferenceForValue, :ptr IPropertyDescription2, :REFPROPVARIANT, :ptr LPWSTR
          ??Interface equ <>
          END_INTERFACE
        IPropertyDescription2Vtbl ends
        IPropertyDescription2 struct
          lpVtbl POINTER ?
        IPropertyDescription2 ends
        ifdef COBJMACROS
          ;[...]
        endif
      endif
    endif
    ifndef __IPropertyDescriptionAliasInfo_INTERFACE_DEFINED__
      __IPropertyDescriptionAliasInfo_INTERFACE_DEFINED__ equ <>
      externdef IID_IPropertyDescriptionAliasInfo:IID
      if Defined(__cplusplus) and  not Defined(CINTERFACE)
        ;[...]
      else
        IPropertyDescriptionAliasInfoVtbl struct
          BEGIN_INTERFACE
          ??Interface equ <IPropertyDescriptionAliasInfoVtbl>
          STD_METHOD QueryInterface, :ptr IPropertyDescriptionAliasInfo, :REFIID, :ptr ptr
          STD_METHOD AddRef, :ptr IPropertyDescriptionAliasInfo
          STD_METHOD Release, :ptr IPropertyDescriptionAliasInfo
          STD_METHOD GetPropertyKey, :ptr IPropertyDescriptionAliasInfo, :ptr PROPERTYKEY
          STD_METHOD GetCanonicalName, :ptr IPropertyDescriptionAliasInfo, :ptr LPWSTR
          STD_METHOD GetPropertyType, :ptr IPropertyDescriptionAliasInfo, :ptr VARTYPE
          STD_METHOD GetDisplayName, :ptr IPropertyDescriptionAliasInfo, :ptr LPWSTR
          STD_METHOD GetEditInvitation, :ptr IPropertyDescriptionAliasInfo, :ptr LPWSTR
          STD_METHOD GetTypeFlags, :ptr IPropertyDescriptionAliasInfo, :PROPDESC_TYPE_FLAGS, :ptr PROPDESC_TYPE_FLAGS
          STD_METHOD GetViewFlags, :ptr IPropertyDescriptionAliasInfo, :ptr PROPDESC_VIEW_FLAGS
          STD_METHOD GetDefaultColumnWidth, :ptr IPropertyDescriptionAliasInfo, :ptr UINT
          STD_METHOD GetDisplayType, :ptr IPropertyDescriptionAliasInfo, :ptr PROPDESC_DISPLAYTYPE
          STD_METHOD GetColumnState, :ptr IPropertyDescriptionAliasInfo, :ptr SHCOLSTATEF
          STD_METHOD GetGroupingRange, :ptr IPropertyDescriptionAliasInfo, :ptr PROPDESC_GROUPING_RANGE
          STD_METHOD GetRelativeDescriptionType, :ptr IPropertyDescriptionAliasInfo, :ptr PROPDESC_RELATIVEDESCRIPTION_TYPE
          STD_METHOD GetRelativeDescription, :ptr IPropertyDescriptionAliasInfo, :REFPROPVARIANT, :REFPROPVARIANT, :ptr LPWSTR, :ptr LPWSTR
          STD_METHOD GetSortDescription, :ptr IPropertyDescriptionAliasInfo, :ptr PROPDESC_SORTDESCRIPTION
          STD_METHOD GetSortDescriptionLabel, :ptr IPropertyDescriptionAliasInfo, :BOOL, :ptr LPWSTR
          STD_METHOD GetAggregationType, :ptr IPropertyDescriptionAliasInfo, :ptr PROPDESC_AGGREGATION_TYPE
          STD_METHOD GetConditionType, :ptr IPropertyDescriptionAliasInfo, :ptr PROPDESC_CONDITION_TYPE, :ptr CONDITION_OPERATION
          STD_METHOD GetEnumTypeList, :ptr IPropertyDescriptionAliasInfo, :REFIID, :ptr ptr
          STD_METHOD CoerceToCanonicalValue, :ptr IPropertyDescriptionAliasInfo, :ptr PROPVARIANT
          STD_METHOD FormatForDisplay, :ptr IPropertyDescriptionAliasInfo, :REFPROPVARIANT, :PROPDESC_FORMAT_FLAGS, :ptr LPWSTR
          STD_METHOD IsValueCanonical, :ptr IPropertyDescriptionAliasInfo, :REFPROPVARIANT
          STD_METHOD GetSortByAlias, :ptr IPropertyDescriptionAliasInfo, :REFIID, :ptr ptr
          STD_METHOD GetAdditionalSortByAliases, :ptr IPropertyDescriptionAliasInfo, :REFIID, :ptr ptr
          ??Interface equ <>
          END_INTERFACE
        IPropertyDescriptionAliasInfoVtbl ends
        IPropertyDescriptionAliasInfo struct
          lpVtbl POINTER ?
        IPropertyDescriptionAliasInfo ends
        ifdef COBJMACROS
          ;[...]
        endif
      endif
    endif
    ifndef __IPropertyDescriptionSearchInfo_INTERFACE_DEFINED__
      __IPropertyDescriptionSearchInfo_INTERFACE_DEFINED__ equ <>
      PROPDESC_SEARCHINFO_FLAGS typedef SDWORD
      PDSIF_DEFAULT equ 0
      PDSIF_ININVERTEDINDEX equ 1h
      PDSIF_ISCOLUMN equ 2h
      PDSIF_ISCOLUMNSPARSE equ 4h
      PDSIF_ALWAYSINCLUDE equ 8h
      PDSIF_USEFORTYPEAHEAD equ 10h
      
      DEFINE_ENUM_FLAG_OPERATORS(PROPDESC_SEARCHINFO_FLAGS)
      PROPDESC_COLUMNINDEX_TYPE typedef SDWORD
      PDCIT_NONE equ 0
      PDCIT_ONDISK equ 1
      PDCIT_INMEMORY equ 2
      PDCIT_ONDEMAND equ 3
      PDCIT_ONDISKALL equ 4
      PDCIT_ONDISKVECTOR equ 5
      
      externdef IID_IPropertyDescriptionSearchInfo:IID
      if Defined(__cplusplus) and  not Defined(CINTERFACE)
        ;[...]
      else
        IPropertyDescriptionSearchInfoVtbl struct
          BEGIN_INTERFACE
          ??Interface equ <IPropertyDescriptionSearchInfoVtbl>
          STD_METHOD QueryInterface, :ptr IPropertyDescriptionSearchInfo, :REFIID, :ptr ptr
          STD_METHOD AddRef, :ptr IPropertyDescriptionSearchInfo
          STD_METHOD Release, :ptr IPropertyDescriptionSearchInfo
          STD_METHOD GetPropertyKey, :ptr IPropertyDescriptionSearchInfo, :ptr PROPERTYKEY
          STD_METHOD GetCanonicalName, :ptr IPropertyDescriptionSearchInfo, :ptr LPWSTR
          STD_METHOD GetPropertyType, :ptr IPropertyDescriptionSearchInfo, :ptr VARTYPE
          STD_METHOD GetDisplayName, :ptr IPropertyDescriptionSearchInfo, :ptr LPWSTR
          STD_METHOD GetEditInvitation, :ptr IPropertyDescriptionSearchInfo, :ptr LPWSTR
          STD_METHOD GetTypeFlags, :ptr IPropertyDescriptionSearchInfo, :PROPDESC_TYPE_FLAGS, :ptr PROPDESC_TYPE_FLAGS
          STD_METHOD GetViewFlags, :ptr IPropertyDescriptionSearchInfo, :ptr PROPDESC_VIEW_FLAGS
          STD_METHOD GetDefaultColumnWidth, :ptr IPropertyDescriptionSearchInfo, :ptr UINT
          STD_METHOD GetDisplayType, :ptr IPropertyDescriptionSearchInfo, :ptr PROPDESC_DISPLAYTYPE
          STD_METHOD GetColumnState, :ptr IPropertyDescriptionSearchInfo, :ptr SHCOLSTATEF
          STD_METHOD GetGroupingRange, :ptr IPropertyDescriptionSearchInfo, :ptr PROPDESC_GROUPING_RANGE
          STD_METHOD GetRelativeDescriptionType, :ptr IPropertyDescriptionSearchInfo, :ptr PROPDESC_RELATIVEDESCRIPTION_TYPE
          STD_METHOD GetRelativeDescription, :ptr IPropertyDescriptionSearchInfo, :REFPROPVARIANT, :REFPROPVARIANT, :ptr LPWSTR, :ptr LPWSTR
          STD_METHOD GetSortDescription, :ptr IPropertyDescriptionSearchInfo, :ptr PROPDESC_SORTDESCRIPTION
          STD_METHOD GetSortDescriptionLabel, :ptr IPropertyDescriptionSearchInfo, :BOOL, :ptr LPWSTR
          STD_METHOD GetAggregationType, :ptr IPropertyDescriptionSearchInfo, :ptr PROPDESC_AGGREGATION_TYPE
          STD_METHOD GetConditionType, :ptr IPropertyDescriptionSearchInfo, :ptr PROPDESC_CONDITION_TYPE, :ptr CONDITION_OPERATION
          STD_METHOD GetEnumTypeList, :ptr IPropertyDescriptionSearchInfo, :REFIID, :ptr ptr
          STD_METHOD CoerceToCanonicalValue, :ptr IPropertyDescriptionSearchInfo, :ptr PROPVARIANT
          STD_METHOD FormatForDisplay, :ptr IPropertyDescriptionSearchInfo, :REFPROPVARIANT, :PROPDESC_FORMAT_FLAGS, :ptr LPWSTR
          STD_METHOD IsValueCanonical, :ptr IPropertyDescriptionSearchInfo, :REFPROPVARIANT
          STD_METHOD GetSearchInfoFlags, :ptr IPropertyDescriptionSearchInfo, :ptr PROPDESC_SEARCHINFO_FLAGS
          STD_METHOD GetColumnIndexType, :ptr IPropertyDescriptionSearchInfo, :ptr PROPDESC_COLUMNINDEX_TYPE
          STD_METHOD GetProjectionString, :ptr IPropertyDescriptionSearchInfo, :ptr LPWSTR
          STD_METHOD GetMaxSize, :ptr IPropertyDescriptionSearchInfo, :ptr UINT
          ??Interface equ <>
          END_INTERFACE
        IPropertyDescriptionSearchInfoVtbl ends
        IPropertyDescriptionSearchInfo struct
          lpVtbl POINTER ?
        IPropertyDescriptionSearchInfo ends
        ifdef COBJMACROS
          ;[...]
        endif
      endif
    endif
    ifndef __IPropertyDescriptionRelatedPropertyInfo_INTERFACE_DEFINED__
      __IPropertyDescriptionRelatedPropertyInfo_INTERFACE_DEFINED__ equ <>
      externdef IID_IPropertyDescriptionRelatedPropertyInfo:IID
      if Defined(__cplusplus) and  not Defined(CINTERFACE)
        ;[...]
      else
        IPropertyDescriptionRelatedPropertyInfoVtbl struct
          BEGIN_INTERFACE
          ??Interface equ <IPropertyDescriptionRelatedPropertyInfoVtbl>
          STD_METHOD QueryInterface, :ptr IPropertyDescriptionRelatedPropertyInfo, :REFIID, :ptr ptr
          STD_METHOD AddRef, :ptr IPropertyDescriptionRelatedPropertyInfo
          STD_METHOD Release, :ptr IPropertyDescriptionRelatedPropertyInfo
          STD_METHOD GetPropertyKey, :ptr IPropertyDescriptionRelatedPropertyInfo, :ptr PROPERTYKEY
          STD_METHOD GetCanonicalName, :ptr IPropertyDescriptionRelatedPropertyInfo, :ptr LPWSTR
          STD_METHOD GetPropertyType, :ptr IPropertyDescriptionRelatedPropertyInfo, :ptr VARTYPE
          STD_METHOD GetDisplayName, :ptr IPropertyDescriptionRelatedPropertyInfo, :ptr LPWSTR
          STD_METHOD GetEditInvitation, :ptr IPropertyDescriptionRelatedPropertyInfo, :ptr LPWSTR
          STD_METHOD GetTypeFlags, :ptr IPropertyDescriptionRelatedPropertyInfo, :PROPDESC_TYPE_FLAGS, :ptr PROPDESC_TYPE_FLAGS
          STD_METHOD GetViewFlags, :ptr IPropertyDescriptionRelatedPropertyInfo, :ptr PROPDESC_VIEW_FLAGS
          STD_METHOD GetDefaultColumnWidth, :ptr IPropertyDescriptionRelatedPropertyInfo, :ptr UINT
          STD_METHOD GetDisplayType, :ptr IPropertyDescriptionRelatedPropertyInfo, :ptr PROPDESC_DISPLAYTYPE
          STD_METHOD GetColumnState, :ptr IPropertyDescriptionRelatedPropertyInfo, :ptr SHCOLSTATEF
          STD_METHOD GetGroupingRange, :ptr IPropertyDescriptionRelatedPropertyInfo, :ptr PROPDESC_GROUPING_RANGE
          STD_METHOD GetRelativeDescriptionType, :ptr IPropertyDescriptionRelatedPropertyInfo, :ptr PROPDESC_RELATIVEDESCRIPTION_TYPE
          STD_METHOD GetRelativeDescription, :ptr IPropertyDescriptionRelatedPropertyInfo, :REFPROPVARIANT, :REFPROPVARIANT, :ptr LPWSTR, :ptr LPWSTR
          STD_METHOD GetSortDescription, :ptr IPropertyDescriptionRelatedPropertyInfo, :ptr PROPDESC_SORTDESCRIPTION
          STD_METHOD GetSortDescriptionLabel, :ptr IPropertyDescriptionRelatedPropertyInfo, :BOOL, :ptr LPWSTR
          STD_METHOD GetAggregationType, :ptr IPropertyDescriptionRelatedPropertyInfo, :ptr PROPDESC_AGGREGATION_TYPE
          STD_METHOD GetConditionType, :ptr IPropertyDescriptionRelatedPropertyInfo, :ptr PROPDESC_CONDITION_TYPE, :ptr CONDITION_OPERATION
          STD_METHOD GetEnumTypeList, :ptr IPropertyDescriptionRelatedPropertyInfo, :REFIID, :ptr ptr
          STD_METHOD CoerceToCanonicalValue, :ptr IPropertyDescriptionRelatedPropertyInfo, :ptr PROPVARIANT
          STD_METHOD FormatForDisplay, :ptr IPropertyDescriptionRelatedPropertyInfo, :REFPROPVARIANT, :PROPDESC_FORMAT_FLAGS, :ptr LPWSTR
          STD_METHOD IsValueCanonical, :ptr IPropertyDescriptionRelatedPropertyInfo, :REFPROPVARIANT
          STD_METHOD GetRelatedProperty, :ptr IPropertyDescriptionRelatedPropertyInfo, :LPCWSTR, :REFIID, :ptr ptr
          ??Interface equ <>
          END_INTERFACE
        IPropertyDescriptionRelatedPropertyInfoVtbl ends
        IPropertyDescriptionRelatedPropertyInfo struct
          lpVtbl POINTER ?
        IPropertyDescriptionRelatedPropertyInfo ends
        ifdef COBJMACROS
          ;[...]
        endif
      endif
    endif
    PROPDESC_ENUMFILTER typedef SDWORD
    PDEF_ALL equ 0
    PDEF_SYSTEM equ 1
    PDEF_NONSYSTEM equ 2
    PDEF_VIEWABLE equ 3
    PDEF_QUERYABLE equ 4
    PDEF_INFULLTEXTQUERY equ 5
    PDEF_COLUMN equ 6
    
    externdef __MIDL_itf_propsys_0000_0017_v0_0_c_ifspec:RPC_IF_HANDLE
    externdef __MIDL_itf_propsys_0000_0017_v0_0_s_ifspec:RPC_IF_HANDLE
    ifndef __IPropertySystem_INTERFACE_DEFINED__
      __IPropertySystem_INTERFACE_DEFINED__ equ <>
      externdef IID_IPropertySystem:IID
      if Defined(__cplusplus) and  not Defined(CINTERFACE)
        ;[...]
      else
        IPropertySystemVtbl struct
          BEGIN_INTERFACE
          ??Interface equ <IPropertySystemVtbl>
          STD_METHOD QueryInterface, :ptr IPropertySystem, :REFIID, :ptr ptr
          STD_METHOD AddRef, :ptr IPropertySystem
          STD_METHOD Release, :ptr IPropertySystem
          STD_METHOD GetPropertyDescription, :ptr IPropertySystem, :REFPROPERTYKEY, :REFIID, :ptr ptr
          STD_METHOD GetPropertyDescriptionByName, :ptr IPropertySystem, :LPCWSTR, :REFIID, :ptr ptr
          STD_METHOD GetPropertyDescriptionListFromString, :ptr IPropertySystem, :LPCWSTR, :REFIID, :ptr ptr
          STD_METHOD EnumeratePropertyDescriptions, :ptr IPropertySystem, :PROPDESC_ENUMFILTER, :REFIID, :ptr ptr
          STD_METHOD FormatForDisplay, :ptr IPropertySystem, :REFPROPERTYKEY, :REFPROPVARIANT, :PROPDESC_FORMAT_FLAGS, :LPWSTR, :DWORD
          STD_METHOD FormatForDisplayAlloc, :ptr IPropertySystem, :REFPROPERTYKEY, :REFPROPVARIANT, :PROPDESC_FORMAT_FLAGS, :ptr LPWSTR
          STD_METHOD RegisterPropertySchema, :ptr IPropertySystem, :LPCWSTR
          STD_METHOD UnregisterPropertySchema, :ptr IPropertySystem, :LPCWSTR
          STD_METHOD RefreshPropertySchema, :ptr IPropertySystem
          ??Interface equ <>
          END_INTERFACE
        IPropertySystemVtbl ends
        IPropertySystem struct
          lpVtbl POINTER ?
        IPropertySystem ends
        ifdef COBJMACROS
          ;[...]
        endif
      endif
    endif
    ifndef __IPropertyDescriptionList_INTERFACE_DEFINED__
      __IPropertyDescriptionList_INTERFACE_DEFINED__ equ <>
      externdef IID_IPropertyDescriptionList:IID
      if Defined(__cplusplus) and  not Defined(CINTERFACE)
        ;[...]
      else
        IPropertyDescriptionListVtbl struct
          BEGIN_INTERFACE
          ??Interface equ <IPropertyDescriptionListVtbl>
          STD_METHOD QueryInterface, :ptr IPropertyDescriptionList, :REFIID, :ptr ptr
          STD_METHOD AddRef, :ptr IPropertyDescriptionList
          STD_METHOD Release, :ptr IPropertyDescriptionList
          STD_METHOD GetCount, :ptr IPropertyDescriptionList, :ptr UINT
          STD_METHOD GetAt, :ptr IPropertyDescriptionList, :UINT, :REFIID, :ptr ptr
          ??Interface equ <>
          END_INTERFACE
        IPropertyDescriptionListVtbl ends
        IPropertyDescriptionList struct
          lpVtbl POINTER ?
        IPropertyDescriptionList ends
        ifdef COBJMACROS
          ;[...]
        endif
      endif
    endif
    ifndef __IPropertyStoreFactory_INTERFACE_DEFINED__
      __IPropertyStoreFactory_INTERFACE_DEFINED__ equ <>
      externdef IID_IPropertyStoreFactory:IID
      if Defined(__cplusplus) and  not Defined(CINTERFACE)
        ;[...]
      else
        IPropertyStoreFactoryVtbl struct
          BEGIN_INTERFACE
          ??Interface equ <IPropertyStoreFactoryVtbl>
          STD_METHOD QueryInterface, :ptr IPropertyStoreFactory, :REFIID, :ptr ptr
          STD_METHOD AddRef, :ptr IPropertyStoreFactory
          STD_METHOD Release, :ptr IPropertyStoreFactory
          STD_METHOD GetPropertyStore, :ptr IPropertyStoreFactory, :GETPROPERTYSTOREFLAGS, :ptr IUnknown, :REFIID, :ptr ptr
          STD_METHOD GetPropertyStoreForKeys, :ptr IPropertyStoreFactory, :ptr PROPERTYKEY, :UINT, :GETPROPERTYSTOREFLAGS, :REFIID, :ptr ptr
          ??Interface equ <>
          END_INTERFACE
        IPropertyStoreFactoryVtbl ends
        IPropertyStoreFactory struct
          lpVtbl POINTER ?
        IPropertyStoreFactory ends
        ifdef COBJMACROS
          ;[...]
        endif
      endif
    endif
    ifndef __IDelayedPropertyStoreFactory_INTERFACE_DEFINED__
      __IDelayedPropertyStoreFactory_INTERFACE_DEFINED__ equ <>
      externdef IID_IDelayedPropertyStoreFactory:IID
      if Defined(__cplusplus) and  not Defined(CINTERFACE)
        ;[...]
      else
        IDelayedPropertyStoreFactoryVtbl struct
          BEGIN_INTERFACE
          ??Interface equ <IDelayedPropertyStoreFactoryVtbl>
          STD_METHOD QueryInterface, :ptr IDelayedPropertyStoreFactory, :REFIID, :ptr ptr
          STD_METHOD AddRef, :ptr IDelayedPropertyStoreFactory
          STD_METHOD Release, :ptr IDelayedPropertyStoreFactory
          STD_METHOD GetPropertyStore, :ptr IDelayedPropertyStoreFactory, :GETPROPERTYSTOREFLAGS, :ptr IUnknown, :REFIID, :ptr ptr
          STD_METHOD GetPropertyStoreForKeys, :ptr IDelayedPropertyStoreFactory, :ptr PROPERTYKEY, :UINT, :GETPROPERTYSTOREFLAGS, :REFIID, :ptr ptr
          STD_METHOD GetDelayedPropertyStore, :ptr IDelayedPropertyStoreFactory, :GETPROPERTYSTOREFLAGS, :DWORD, :REFIID, :ptr ptr
          ??Interface equ <>
          END_INTERFACE
        IDelayedPropertyStoreFactoryVtbl ends
        IDelayedPropertyStoreFactory struct
          lpVtbl POINTER ?
        IDelayedPropertyStoreFactory ends
        ifdef COBJMACROS
          ;[...]
        endif
      endif
    endif
    _PERSIST_SPROPSTORE_FLAGS typedef SDWORD
    FPSPS_DEFAULT equ 0
    FPSPS_READONLY equ 1h
    FPSPS_TREAT_NEW_VALUES_AS_DIRTY equ 2h
    
    PERSIST_SPROPSTORE_FLAGS typedef SDWORD
    SERIALIZEDPROPSTORAGE equ <>
    
    PUSERIALIZEDPROPSTORAGE typedef ptr SERIALIZEDPROPSTORAGE
    PCUSERIALIZEDPROPSTORAGE typedef ptr SERIALIZEDPROPSTORAGE
    externdef __MIDL_itf_propsys_0000_0021_v0_0_c_ifspec:RPC_IF_HANDLE
    externdef __MIDL_itf_propsys_0000_0021_v0_0_s_ifspec:RPC_IF_HANDLE
    ifndef __IPersistSerializedPropStorage_INTERFACE_DEFINED__
      __IPersistSerializedPropStorage_INTERFACE_DEFINED__ equ <>
      externdef IID_IPersistSerializedPropStorage:IID
      if Defined(__cplusplus) and  not Defined(CINTERFACE)
        ;[...]
      else
        IPersistSerializedPropStorageVtbl struct
          BEGIN_INTERFACE
          ??Interface equ <IPersistSerializedPropStorageVtbl>
          STD_METHOD QueryInterface, :ptr IPersistSerializedPropStorage, :REFIID, :ptr ptr
          STD_METHOD AddRef, :ptr IPersistSerializedPropStorage
          STD_METHOD Release, :ptr IPersistSerializedPropStorage
          STD_METHOD SetFlags, :ptr IPersistSerializedPropStorage, :PERSIST_SPROPSTORE_FLAGS
          STD_METHOD SetPropertyStorage, :ptr IPersistSerializedPropStorage, :PCUSERIALIZEDPROPSTORAGE, :DWORD
          STD_METHOD GetPropertyStorage, :ptr IPersistSerializedPropStorage, :ptr ptr SERIALIZEDPROPSTORAGE, :ptr DWORD
          ??Interface equ <>
          END_INTERFACE
        IPersistSerializedPropStorageVtbl ends
        IPersistSerializedPropStorage struct
          lpVtbl POINTER ?
        IPersistSerializedPropStorage ends
        ifdef COBJMACROS
          ;[...]
        endif
      endif
    endif
    ifndef __IPersistSerializedPropStorage2_INTERFACE_DEFINED__
      __IPersistSerializedPropStorage2_INTERFACE_DEFINED__ equ <>
      externdef IID_IPersistSerializedPropStorage2:IID
      if Defined(__cplusplus) and  not Defined(CINTERFACE)
        ;[...]
      else
        IPersistSerializedPropStorage2Vtbl struct
          BEGIN_INTERFACE
          ??Interface equ <IPersistSerializedPropStorage2Vtbl>
          STD_METHOD QueryInterface, :ptr IPersistSerializedPropStorage2, :REFIID, :ptr ptr
          STD_METHOD AddRef, :ptr IPersistSerializedPropStorage2
          STD_METHOD Release, :ptr IPersistSerializedPropStorage2
          STD_METHOD SetFlags, :ptr IPersistSerializedPropStorage2, :PERSIST_SPROPSTORE_FLAGS
          STD_METHOD SetPropertyStorage, :ptr IPersistSerializedPropStorage2, :PCUSERIALIZEDPROPSTORAGE, :DWORD
          STD_METHOD GetPropertyStorage, :ptr IPersistSerializedPropStorage2, :ptr ptr SERIALIZEDPROPSTORAGE, :ptr DWORD
          STD_METHOD GetPropertyStorageSize, :ptr IPersistSerializedPropStorage2, :ptr DWORD
          STD_METHOD GetPropertyStorageBuffer, :ptr IPersistSerializedPropStorage2, :ptr SERIALIZEDPROPSTORAGE, :DWORD, :ptr DWORD
          ??Interface equ <>
          END_INTERFACE
        IPersistSerializedPropStorage2Vtbl ends
        IPersistSerializedPropStorage2 struct
          lpVtbl POINTER ?
        IPersistSerializedPropStorage2 ends
        ifdef COBJMACROS
          ;[...]
        endif
      endif
    endif
    ifndef __IPropertySystemChangeNotify_INTERFACE_DEFINED__
      __IPropertySystemChangeNotify_INTERFACE_DEFINED__ equ <>
      externdef IID_IPropertySystemChangeNotify:IID
      if Defined(__cplusplus) and  not Defined(CINTERFACE)
        ;[...]
      else
        IPropertySystemChangeNotifyVtbl struct
          BEGIN_INTERFACE
          ??Interface equ <IPropertySystemChangeNotifyVtbl>
          STD_METHOD QueryInterface, :ptr IPropertySystemChangeNotify, :REFIID, :ptr ptr
          STD_METHOD AddRef, :ptr IPropertySystemChangeNotify
          STD_METHOD Release, :ptr IPropertySystemChangeNotify
          STD_METHOD SchemaRefreshed, :ptr IPropertySystemChangeNotify
          ??Interface equ <>
          END_INTERFACE
        IPropertySystemChangeNotifyVtbl ends
        IPropertySystemChangeNotify struct
          lpVtbl POINTER ?
        IPropertySystemChangeNotify ends
        ifdef COBJMACROS
          ;[...]
        endif
      endif
    endif
    ifndef __ICreateObject_INTERFACE_DEFINED__
      __ICreateObject_INTERFACE_DEFINED__ equ <>
      externdef IID_ICreateObject:IID
      if Defined(__cplusplus) and  not Defined(CINTERFACE)
        ;[...]
      else
        ICreateObjectVtbl struct
          BEGIN_INTERFACE
          ??Interface equ <ICreateObjectVtbl>
          STD_METHOD QueryInterface, :ptr ICreateObject, :REFIID, :ptr ptr
          STD_METHOD AddRef, :ptr ICreateObject
          STD_METHOD Release, :ptr ICreateObject
          STD_METHOD CreateObject, :ptr ICreateObject, :REFCLSID, :ptr IUnknown, :REFIID, :ptr ptr
          ??Interface equ <>
          END_INTERFACE
        ICreateObjectVtbl ends
        ICreateObject struct
          lpVtbl POINTER ?
        ICreateObject ends
        ifdef COBJMACROS
          ;[...]
        endif
      endif
    endif
    @DefProto DllImport, PSFormatForDisplay, WIN_STD_CALL_CONV,, <:REFPROPERTYKEY, :REFPROPVARIANT, :PROPDESC_FORMAT_FLAGS, :LPWSTR, :DWORD>, 20
    @DefProto DllImport, PSFormatForDisplayAlloc, WIN_STD_CALL_CONV,, <:REFPROPERTYKEY, :REFPROPVARIANT, :PROPDESC_FORMAT_FLAGS, :ptr PWSTR>, 16
    @DefProto DllImport, PSFormatPropertyValue, WIN_STD_CALL_CONV,, <:ptr IPropertyStore, :ptr IPropertyDescription, :PROPDESC_FORMAT_FLAGS, :ptr LPWSTR>, 16
    @DefProto DllImport, PSGetImageReferenceForValue, WIN_STD_CALL_CONV,, <:REFPROPERTYKEY, :REFPROPVARIANT, :ptr PWSTR>, 12
    PKEY_PIDSTR_MAX equ 10
    GUIDSTRING_MAX equ (1 + 8 + 1 + 4 + 1 + 4 + 1 + 4 + 1 + 12 + 1 + 1)
    PKEYSTR_MAX equ (GUIDSTRING_MAX + 1 + PKEY_PIDSTR_MAX)
    @DefProto DllImport, PSStringFromPropertyKey, WIN_STD_CALL_CONV,, <:REFPROPERTYKEY, :LPWSTR, :UINT>, 12
    @DefProto DllImport, PSPropertyKeyFromString, WIN_STD_CALL_CONV,, <:LPCWSTR, :ptr PROPERTYKEY>, 8
  endif
  if WINAPI_FAMILY_PARTITION(WINAPI_PARTITION_APP)
    @DefProto DllImport, PSCreateMemoryPropertyStore, WIN_STD_CALL_CONV,, <:REFIID, :ptr ptr>, 8
  endif
  if WINAPI_FAMILY_PARTITION(WINAPI_PARTITION_DESKTOP)
    @DefProto DllImport, PSCreateDelayedMultiplexPropertyStore, WIN_STD_CALL_CONV,, <:GETPROPERTYSTOREFLAGS, :ptr IDelayedPropertyStoreFactory, :ptr DWORD, :DWORD, :REFIID, :ptr ptr>, 24
    @DefProto DllImport, PSCreateMultiplexPropertyStore, WIN_STD_CALL_CONV,, <:ptr ptr IUnknown, :DWORD, :REFIID, :ptr ptr>, 16
    @DefProto DllImport, PSCreatePropertyChangeArray, WIN_STD_CALL_CONV,, <:ptr PROPERTYKEY, :ptr PKA_FLAGS, :ptr PROPVARIANT, :UINT, :REFIID, :ptr ptr>, 24
    @DefProto DllImport, PSCreateSimplePropertyChange, WIN_STD_CALL_CONV,, <:PKA_FLAGS, :REFPROPERTYKEY, :REFPROPVARIANT, :REFIID, :ptr ptr>, 20
    @DefProto DllImport, PSGetPropertyDescription, WIN_STD_CALL_CONV,, <:REFPROPERTYKEY, :REFIID, :ptr ptr>, 12
    @DefProto DllImport, PSGetPropertyDescriptionByName, WIN_STD_CALL_CONV,, <:LPCWSTR, :REFIID, :ptr ptr>, 12
    @DefProto DllImport, PSLookupPropertyHandlerCLSID, WIN_STD_CALL_CONV,, <:PCWSTR, :ptr CLSID>, 8
    @DefProto DllImport, PSGetItemPropertyHandler, WIN_STD_CALL_CONV,, <:ptr IUnknown, :BOOL, :REFIID, :ptr ptr>, 16
    @DefProto DllImport, PSGetItemPropertyHandlerWithCreateObject, WIN_STD_CALL_CONV,, <:ptr IUnknown, :BOOL, :ptr IUnknown, :REFIID, :ptr ptr>, 20
    @DefProto DllImport, PSGetPropertyValue, WIN_STD_CALL_CONV,, <:ptr IPropertyStore, :ptr IPropertyDescription, :ptr PROPVARIANT>, 12
    @DefProto DllImport, PSSetPropertyValue, WIN_STD_CALL_CONV,, <:ptr IPropertyStore, :ptr IPropertyDescription, :REFPROPVARIANT>, 12
    @DefProto DllImport, PSRegisterPropertySchema, WIN_STD_CALL_CONV,, <:PCWSTR>, 4
    @DefProto DllImport, PSUnregisterPropertySchema, WIN_STD_CALL_CONV,, <:PCWSTR>, 4
    @DefProto DllImport, PSRefreshPropertySchema, WIN_STD_CALL_CONV,, <>, 0
    @DefProto DllImport, PSEnumeratePropertyDescriptions, WIN_STD_CALL_CONV,, <:PROPDESC_ENUMFILTER, :REFIID, :ptr ptr>, 12
    @DefProto DllImport, PSGetPropertyKeyFromName, WIN_STD_CALL_CONV,, <:PCWSTR, :ptr PROPERTYKEY>, 8
    @DefProto DllImport, PSGetNameFromPropertyKey, WIN_STD_CALL_CONV,, <:REFPROPERTYKEY, :ptr PWSTR>, 8
    @DefProto DllImport, PSCoerceToCanonicalValue, WIN_STD_CALL_CONV,, <:REFPROPERTYKEY, :ptr PROPVARIANT>, 8
    @DefProto DllImport, PSGetPropertyDescriptionListFromString, WIN_STD_CALL_CONV,, <:LPCWSTR, :REFIID, :ptr ptr>, 12
    @DefProto DllImport, PSCreatePropertyStoreFromPropertySetStorage, WIN_STD_CALL_CONV,, <:ptr IPropertySetStorage, :DWORD, :REFIID, :ptr ptr>, 16
  endif
  if WINAPI_FAMILY_PARTITION(WINAPI_PARTITION_APP)
    @DefProto DllImport, PSCreatePropertyStoreFromObject, WIN_STD_CALL_CONV,, <:ptr IUnknown, :DWORD, :REFIID, :ptr ptr>, 16
    @DefProto DllImport, PSCreateAdapterFromPropertyStore, WIN_STD_CALL_CONV,, <:ptr IPropertyStore, :REFIID, :ptr ptr>, 12
  endif
  if WINAPI_FAMILY_PARTITION(WINAPI_PARTITION_DESKTOP)
    @DefProto DllImport, PSGetPropertySystem, WIN_STD_CALL_CONV,, <:REFIID, :ptr ptr>, 8
    @DefProto DllImport, PSGetPropertyFromPropertyStorage, WIN_STD_CALL_CONV,, <:PCUSERIALIZEDPROPSTORAGE, :DWORD, :REFPROPERTYKEY, :ptr PROPVARIANT>, 16
    @DefProto DllImport, PSGetNamedPropertyFromPropertyStorage, WIN_STD_CALL_CONV,, <:PCUSERIALIZEDPROPSTORAGE, :DWORD, :LPCWSTR, :ptr PROPVARIANT>, 16
    @DefProto DllImport, PSPropertyBag_ReadType, WIN_STD_CALL_CONV,, <:ptr IPropertyBag, :LPCWSTR, :ptr VARIANT, :VARTYPE>, 16
    @DefProto DllImport, PSPropertyBag_ReadStr, WIN_STD_CALL_CONV,, <:ptr IPropertyBag, :LPCWSTR, :LPWSTR, :SDWORD>, 16
    @DefProto DllImport, PSPropertyBag_ReadStrAlloc, WIN_STD_CALL_CONV,, <:ptr IPropertyBag, :LPCWSTR, :ptr PWSTR>, 12
    @DefProto DllImport, PSPropertyBag_ReadBSTR, WIN_STD_CALL_CONV,, <:ptr IPropertyBag, :LPCWSTR, :ptr BSTR>, 12
    @DefProto DllImport, PSPropertyBag_WriteStr, WIN_STD_CALL_CONV,, <:ptr IPropertyBag, :LPCWSTR, :LPCWSTR>, 12
    @DefProto DllImport, PSPropertyBag_WriteBSTR, WIN_STD_CALL_CONV,, <:ptr IPropertyBag, :LPCWSTR, :BSTR>, 12
    @DefProto DllImport, PSPropertyBag_ReadInt, WIN_STD_CALL_CONV,, <:ptr IPropertyBag, :LPCWSTR, :ptr INT_>, 12
    @DefProto DllImport, PSPropertyBag_WriteInt, WIN_STD_CALL_CONV,, <:ptr IPropertyBag, :LPCWSTR, :INT_>, 12
    @DefProto DllImport, PSPropertyBag_ReadSHORT, WIN_STD_CALL_CONV,, <:ptr IPropertyBag, :LPCWSTR, :ptr SHORT_>, 12
    @DefProto DllImport, PSPropertyBag_WriteSHORT, WIN_STD_CALL_CONV,, <:ptr IPropertyBag, :LPCWSTR, :SHORT_>, 12
    @DefProto DllImport, PSPropertyBag_ReadLONG, WIN_STD_CALL_CONV,, <:ptr IPropertyBag, :LPCWSTR, :ptr LONG>, 12
    @DefProto DllImport, PSPropertyBag_WriteLONG, WIN_STD_CALL_CONV,, <:ptr IPropertyBag, :LPCWSTR, :LONG>, 12
    @DefProto DllImport, PSPropertyBag_ReadDWORD, WIN_STD_CALL_CONV,, <:ptr IPropertyBag, :LPCWSTR, :ptr DWORD>, 12
    @DefProto DllImport, PSPropertyBag_WriteDWORD, WIN_STD_CALL_CONV,, <:ptr IPropertyBag, :LPCWSTR, :DWORD>, 12
    @DefProto DllImport, PSPropertyBag_ReadBOOL, WIN_STD_CALL_CONV,, <:ptr IPropertyBag, :LPCWSTR, :ptr BOOL>, 12
    @DefProto DllImport, PSPropertyBag_WriteBOOL, WIN_STD_CALL_CONV,, <:ptr IPropertyBag, :LPCWSTR, :BOOL>, 12
    @DefProto DllImport, PSPropertyBag_ReadPOINTL, WIN_STD_CALL_CONV,, <:ptr IPropertyBag, :LPCWSTR, :ptr POINTL>, 12
    @DefProto DllImport, PSPropertyBag_WritePOINTL, WIN_STD_CALL_CONV,, <:ptr IPropertyBag, :LPCWSTR, :ptr POINTL>, 12
    @DefProto DllImport, PSPropertyBag_ReadPOINTS, WIN_STD_CALL_CONV,, <:ptr IPropertyBag, :LPCWSTR, :ptr POINTS>, 12
    @DefProto DllImport, PSPropertyBag_WritePOINTS, WIN_STD_CALL_CONV,, <:ptr IPropertyBag, :LPCWSTR, :ptr POINTS>, 12
    @DefProto DllImport, PSPropertyBag_ReadRECTL, WIN_STD_CALL_CONV,, <:ptr IPropertyBag, :LPCWSTR, :ptr RECTL>, 12
    @DefProto DllImport, PSPropertyBag_WriteRECTL, WIN_STD_CALL_CONV,, <:ptr IPropertyBag, :LPCWSTR, :ptr RECTL>, 12
    @DefProto DllImport, PSPropertyBag_ReadStream, WIN_STD_CALL_CONV,, <:ptr IPropertyBag, :LPCWSTR, :ptr ptr IStream>, 12
    @DefProto DllImport, PSPropertyBag_WriteStream, WIN_STD_CALL_CONV,, <:ptr IPropertyBag, :LPCWSTR, :ptr IStream>, 12
    @DefProto DllImport, PSPropertyBag_Delete, WIN_STD_CALL_CONV,, <:ptr IPropertyBag, :LPCWSTR>, 8
    @DefProto DllImport, PSPropertyBag_ReadULONGLONG, WIN_STD_CALL_CONV,, <:ptr IPropertyBag, :LPCWSTR, :ptr ULONGLONG>, 12
    @DefProto DllImport, PSPropertyBag_WriteULONGLONG, WIN_STD_CALL_CONV,, <:ptr IPropertyBag, :LPCWSTR, :ULONGLONG>, 16
    @DefProto DllImport, PSPropertyBag_ReadUnknown, WIN_STD_CALL_CONV,, <:ptr IPropertyBag, :LPCWSTR, :REFIID, :ptr ptr>, 16
    @DefProto DllImport, PSPropertyBag_WriteUnknown, WIN_STD_CALL_CONV,, <:ptr IPropertyBag, :LPCWSTR, :ptr IUnknown>, 12
    @DefProto DllImport, PSPropertyBag_ReadGUID, WIN_STD_CALL_CONV,, <:ptr IPropertyBag, :LPCWSTR, :ptr GUID>, 12
    @DefProto DllImport, PSPropertyBag_WriteGUID, WIN_STD_CALL_CONV,, <:ptr IPropertyBag, :LPCWSTR, :ptr GUID>, 12
    @DefProto DllImport, PSPropertyBag_ReadPropertyKey, WIN_STD_CALL_CONV,, <:ptr IPropertyBag, :LPCWSTR, :ptr PROPERTYKEY>, 12
    @DefProto DllImport, PSPropertyBag_WritePropertyKey, WIN_STD_CALL_CONV,, <:ptr IPropertyBag, :LPCWSTR, :REFPROPERTYKEY>, 12
    externdef __MIDL_itf_propsys_0000_0025_v0_0_c_ifspec:RPC_IF_HANDLE
    externdef __MIDL_itf_propsys_0000_0025_v0_0_s_ifspec:RPC_IF_HANDLE
    ifndef __PropSysObjects_LIBRARY_DEFINED__
      __PropSysObjects_LIBRARY_DEFINED__ equ <>
      externdef LIBID_PropSysObjects:IID
      externdef CLSID_InMemoryPropertyStore:CLSID
      ifdef __cplusplus
        ;[...]
      endif
      externdef CLSID_InMemoryPropertyStoreMarshalByValue:CLSID
      ifdef __cplusplus
        ;[...]
      endif
      externdef CLSID_PropertySystem:CLSID
      ifdef __cplusplus
        ;[...]
      endif
    endif
    if _MSC_VER ge 1200
    endif
  endif
  externdef __MIDL_itf_propsys_0000_0026_v0_0_c_ifspec:RPC_IF_HANDLE
  externdef __MIDL_itf_propsys_0000_0026_v0_0_s_ifspec:RPC_IF_HANDLE
  BSTR_UserSize proto WIN_STD_CALL_CONV :ptr DWORD, :DWORD, :ptr BSTR
  BSTR_UserMarshal proto WIN_STD_CALL_CONV :ptr DWORD, :ptr BYTE, :ptr BSTR
  BSTR_UserUnmarshal proto WIN_STD_CALL_CONV :ptr DWORD, :ptr BYTE, :ptr BSTR
  BSTR_UserFree proto WIN_STD_CALL_CONV :ptr DWORD, :ptr BSTR
  LPSAFEARRAY_UserSize proto WIN_STD_CALL_CONV :ptr DWORD, :DWORD, :ptr LPSAFEARRAY
  LPSAFEARRAY_UserMarshal proto WIN_STD_CALL_CONV :ptr DWORD, :ptr BYTE, :ptr LPSAFEARRAY
  LPSAFEARRAY_UserUnmarshal proto WIN_STD_CALL_CONV :ptr DWORD, :ptr BYTE, :ptr LPSAFEARRAY
  LPSAFEARRAY_UserFree proto WIN_STD_CALL_CONV :ptr DWORD, :ptr LPSAFEARRAY
  BSTR_UserSize64 proto WIN_STD_CALL_CONV :ptr DWORD, :DWORD, :ptr BSTR
  BSTR_UserMarshal64 proto WIN_STD_CALL_CONV :ptr DWORD, :ptr BYTE, :ptr BSTR
  BSTR_UserUnmarshal64 proto WIN_STD_CALL_CONV :ptr DWORD, :ptr BYTE, :ptr BSTR
  BSTR_UserFree64 proto WIN_STD_CALL_CONV :ptr DWORD, :ptr BSTR
  LPSAFEARRAY_UserSize64 proto WIN_STD_CALL_CONV :ptr DWORD, :DWORD, :ptr LPSAFEARRAY
  LPSAFEARRAY_UserMarshal64 proto WIN_STD_CALL_CONV :ptr DWORD, :ptr BYTE, :ptr LPSAFEARRAY
  LPSAFEARRAY_UserUnmarshal64 proto WIN_STD_CALL_CONV :ptr DWORD, :ptr BYTE, :ptr LPSAFEARRAY
  LPSAFEARRAY_UserFree64 proto WIN_STD_CALL_CONV :ptr DWORD, :ptr LPSAFEARRAY
  IInitializeWithStream_Initialize_Proxy proto WIN_STD_CALL_CONV :ptr IInitializeWithStream, :ptr IStream, :DWORD
  IInitializeWithStream_Initialize_Stub proto WIN_STD_CALL_CONV :ptr IInitializeWithStream, :ptr IStream, :DWORD
  IPropertyDescription_CoerceToCanonicalValue_Proxy proto WIN_STD_CALL_CONV :ptr IPropertyDescription, :ptr PROPVARIANT
  IPropertyDescription_CoerceToCanonicalValue_Stub proto WIN_STD_CALL_CONV :ptr IPropertyDescription, :REFPROPVARIANT, :ptr PROPVARIANT
  ifdef __cplusplus
    ;[...]
  endif
endif

