; ==================================================================================================
; Title:    ResGuard.inc
; Author:   G. Friedrich
; Version:  C.1.0
; Purpose:  Detection of resource leakages using ObjAsm ResGuard.dll.
; Notes:    Version 1.0.0, April 2005
;             - First release.
; ==================================================================================================


ResGuardStart proto
ResGuardStop  proto
ResGuardShow  proto
