; ==================================================================================================
; Title:      GetNetworkTime_Shared.inc
; Author:     G. Friedrich
; Version:    See GetNetworkTime.asm 
; Purpose:    ObjAsm GetNetworkTime Application.
; ==================================================================================================


;General information
APP_TITLE                     textequ   <GetInternetTime>
ABOUT_TEXT                    textequ   <GetInternetTime>
COPYRIGHT                     textequ   <G. Friedrich   January 2021> 
VER_FILEVERSION               equ       1,0,0,0
VER_FILEVERSION_STR           textequ   <1.0>
VER_PRODUCTVERSION            equ       1,0,0,0
VER_PRODUCTVERSION_STR        textequ   <1.0>

;Build information - updated automatically -
BUILD_NUMBER                  equ       3
BUILD_DATE_STR                textequ   <2022-08-08>
BUILD_BITNESS                 equ       32
BUILD_MODE                    equ       DBG

